Subject.create(:code => 101, :name => 'QUIMICA GENERAL')
Subject.create(:code => 125, :name => 'CÁLCULO ELEMENTAL')
Subject.create(:code => 126, :name => 'ALGEBRA Y GEOMETRÍA')
Subject.create(:code => 127, :name => 'INFORMÁTICA I')
Subject.create(:code => 128, :name => 'REPRESENTACIÓN GRAFICA')
Subject.create(:code => 130, :name => 'CÁLCULO AVANZADO')
Subject.create(:code => 131, :name => 'FÍSICA I')
Subject.create(:code => 132, :name => 'INFORMÁTICA II')
Subject.create(:code => 135, :name => 'INTROD.FIL.Y ANTROP.FILOSOFICA')
Subject.create(:code => 207, :name => 'FILOSOFIA II')
Subject.create(:code => 219, :name => 'INFORMATICA')
Subject.create(:code => 223, :name => 'FISICA II')
Subject.create(:code => 225, :name => 'ESTABILIDAD II')
Subject.create(:code => 226, :name => 'MECANICA')
Subject.create(:code => 246, :name => 'FÍSICA II')
Subject.create(:code => 247, :name => 'QUÍMICA GENERAL')
Subject.create(:code => 248, :name => 'MATEMÁTICA SUPERIOR')
Subject.create(:code => 251, :name => 'PROBABILIDAD Y ESTADÍSTICA')
Subject.create(:code => 252, :name => 'ELECTROTECNIA')
Subject.create(:code => 253, :name => 'MECÁNICA')
Subject.create(:code => 254, :name => 'MÉTODOS NUMÉRICOS')
Subject.create(:code => 255, :name => 'LABORATORIO DE INGENIERÍA')
Subject.create(:code => 256, :name => 'FÍSICA III')
Subject.create(:code => 257, :name => 'INGENIERIA, ECONOM.Y SOCIEDAD')
Subject.create(:code => 258, :name => 'ÉTICA Y METAFÍSICA')
Subject.create(:code => 260, :name => 'REPRESENT.GRAFICA APLICADA')
Subject.create(:code => 302, :name => 'BIOLOGIA Y MICROBIOLOGIA')
Subject.create(:code => 303, :name => 'TERMODINAMICA')
Subject.create(:code => 304, :name => 'REDES I')
Subject.create(:code => 305, :name => 'HIGIENE Y SEGURIDAD')
Subject.create(:code => 311, :name => 'INSTRUMENTOS Y MEDICIONES')
Subject.create(:code => 312, :name => 'MUESTREO Y EVAL.AMBIENTAL')
Subject.create(:code => 313, :name => 'TERMODINAMICA')
Subject.create(:code => 314, :name => 'ELECTROTECNIA I')
Subject.create(:code => 318, :name => 'TEOLOGIA I')
Subject.create(:code => 320, :name => 'TERMODINÁMICA')
Subject.create(:code => 321, :name => 'MECANICA DE LOS FLUIDOS')
Subject.create(:code => 322, :name => 'ESTADISTICA I')
Subject.create(:code => 324, :name => 'QUÍMICA DEL AMBIENTE')
Subject.create(:code => 325, :name => 'MUESTREO,EVAL.Y CTROL.AMBIENT.')
Subject.create(:code => 326, :name => 'MICROBIOLOGÍA AMBIENTAL')
Subject.create(:code => 327, :name => 'MECÁNICA DE LOS FLUIDOS')
Subject.create(:code => 328, :name => 'TERMODINÁMICA')
Subject.create(:code => 329, :name => 'REDES I')
Subject.create(:code => 330, :name => 'MAQUINAS Y MOTORES ELÉCTRICOS')
Subject.create(:code => 331, :name => 'ESTRUCTURA DE DATOS')
Subject.create(:code => 332, :name => 'ESTADÍSTICA APLICADA')
Subject.create(:code => 333, :name => 'ECONOMÍA GENERAL Y EMPRESARIA')
Subject.create(:code => 334, :name => 'TECNOLOGÍA MECÁNICA')
Subject.create(:code => 335, :name => 'MECÁNICA DE LOS FLUIDOS')
Subject.create(:code => 351, :name => 'ESTADISTICA')
Subject.create(:code => 352, :name => 'MATEMATICA IV')
Subject.create(:code => 354, :name => 'TERMODINÁMICA')
Subject.create(:code => 358, :name => 'ESTABILIDAD II')
Subject.create(:code => 359, :name => 'TOPOGRAFÍA Y GEODESIA')
Subject.create(:code => 360, :name => 'MECÁNICA DE SUELOS')
Subject.create(:code => 361, :name => 'INSTALACIONES DE EDIFICIOS')
Subject.create(:code => 362, :name => 'TEOLOGÍA FUNDAMENTAL')
Subject.create(:code => 401, :name => 'MECANICA DE LOS FLUIDOS')
Subject.create(:code => 402, :name => 'ELECTROTECNIA II')
Subject.create(:code => 403, :name => 'SIST.TRANSPORTES CONTAMINANTES')
Subject.create(:code => 404, :name => 'CONSTRUCCIONES DE HORMIGON I')
Subject.create(:code => 406, :name => 'BASES DE DATOS')
Subject.create(:code => 407, :name => 'TEOLOGIA II')
Subject.create(:code => 408, :name => 'ELECTROTECNIA')
Subject.create(:code => 409, :name => 'ESTADISTICA II')
Subject.create(:code => 410, :name => 'MECANICA DE SUELOS Y FUNDACIO.')
Subject.create(:code => 412, :name => 'COSTOS INDUSTRIALES')
Subject.create(:code => 413, :name => 'ELEMENTOS DE MAQUINAS')
Subject.create(:code => 414, :name => 'INGENIERÍA DE SOFTWARE II')
Subject.create(:code => 415, :name => 'LEGISLACIÓN PROFESIONAL')
Subject.create(:code => 416, :name => 'COMPLEJIDAD COMPUTACIONAL')
Subject.create(:code => 417, :name => 'REDES III')
Subject.create(:code => 418, :name => 'MAQUINAS TERMICAS')
Subject.create(:code => 419, :name => 'GESTION AMBIENTAL I')
Subject.create(:code => 422, :name => 'INSTALACIONES COMPLEMENTARIAS')
Subject.create(:code => 424, :name => 'CONSTRUC.METALICAS Y DE MADERA')
Subject.create(:code => 426, :name => 'ELECTRÓNICA III')
Subject.create(:code => 427, :name => 'REDES DE COMUN.DIGITALES II')
Subject.create(:code => 428, :name => 'TEORIA Y LABORAT.CTROL.AUTOM.')
Subject.create(:code => 429, :name => 'GESTIÓN AMBIENTAL I')
Subject.create(:code => 430, :name => 'HIGIENE Y SEGURIDAD LABORAL')
Subject.create(:code => 431, :name => 'MODELOS DE TRANSP.DE CONTAM.')
Subject.create(:code => 432, :name => 'ENERGÍA Y MEDIO AMBIENTE')
Subject.create(:code => 436, :name => 'TEOLOGÍA DOGMÁTICA')
Subject.create(:code => 438, :name => 'LEGISLACIÓN PROFESIONAL')
Subject.create(:code => 439, :name => 'ADMINISTRACIÓN DE EMPRESAS')
Subject.create(:code => 440, :name => 'ARQUITECTURA Y URBANISMO')
Subject.create(:code => 443, :name => 'PROY.CALC.ESTRUCT.HORM.II')
Subject.create(:code => 444, :name => 'DISEÑO GEOM.VIAS DE COMUNIC.')
Subject.create(:code => 445, :name => 'FERROCARRILES')
Subject.create(:code => 446, :name => 'PUERTOS Y VIAS NAVEGABLES')
Subject.create(:code => 455, :name => 'INVESTIGACIÓN OPERATIVA')
Subject.create(:code => 458, :name => 'COSTOS PARA INGENIEROS')
Subject.create(:code => 459, :name => 'ORGANIZACIÓN INDUSTRIAL II')
Subject.create(:code => 460, :name => 'PROCESOS INDUSTRIALES II')
Subject.create(:code => 461, :name => 'MAQUINAS TÉRMICAS')
Subject.create(:code => 462, :name => 'ANALISIS DE DECISIONES Y SIM.')
Subject.create(:code => 463, :name => 'PROCESOS INDUSTRIALES II')
Subject.create(:code => 503, :name => 'ORGAN.PROGRAM.CONTROL DE OBRAS')
Subject.create(:code => 504, :name => 'PUERTOS Y VIAS NAVEGABLES')
Subject.create(:code => 507, :name => 'DERECHO,POL.ORDENAM.AMBIENT.')
Subject.create(:code => 509, :name => 'DERECHO Y POLITICA AMBIENTAL')
Subject.create(:code => 510, :name => 'INGENIERIA ECONOMICA')
Subject.create(:code => 511, :name => 'GESTION DE LA CALIDAD')
Subject.create(:code => 512, :name => 'HIDRAULICA APLICADA')
Subject.create(:code => 513, :name => 'INGENIERIA SANITARIA')
Subject.create(:code => 514, :name => 'SIST.VIDEO Y PROCES.DE IMAGEN.')
Subject.create(:code => 516, :name => 'CONSTRUCCIONES DE HORMIGON II')
Subject.create(:code => 517, :name => 'PROYECTO DE ESTRUCTURAS')
Subject.create(:code => 518, :name => 'OPTOELECTRONICA')
Subject.create(:code => 520, :name => 'ADMINISTRACIÓN DE EMPRESAS')
Subject.create(:code => 521, :name => 'DIR.PROYECTOS DE SISTEMAS')
Subject.create(:code => 522, :name => 'INSTRUMENTACION Y CONTROL')
Subject.create(:code => 523, :name => 'SISTEMAS DIGITALES APLICADOS')
Subject.create(:code => 524, :name => 'AUDITORIA INFORMÁTICA')
Subject.create(:code => 527, :name => 'PROYECTO DE PLANTA')
Subject.create(:code => 528, :name => 'TEOLOGIA III')
Subject.create(:code => 531, :name => 'LOGISTICA')
Subject.create(:code => 532, :name => 'LEGISLACION GENERAL Y LABORAL')
Subject.create(:code => 533, :name => 'CARRETERAS Y AEROPUERTOS')
Subject.create(:code => 534, :name => 'COMUNICACIONES ÓPTICAS')
Subject.create(:code => 535, :name => 'ADMINISTRACIÓN DE EMPRESAS')
Subject.create(:code => 536, :name => 'ELECTRONICA Y CTROL.INDUSTRIAL')
Subject.create(:code => 537, :name => 'POLIT.Y LEGISLACION AMBIENTAL')
Subject.create(:code => 538, :name => 'LEGISLACIÓN PROFESIONAL')
Subject.create(:code => 539, :name => 'TEOL.MORAL Y DOCTR.SOC.IGLESIA')
Subject.create(:code => 540, :name => 'GESTIÓN DE LA CALIDAD')
Subject.create(:code => 541, :name => 'INGENIERÍA ECONÓMICA')
Subject.create(:code => 542, :name => 'HIG.SEGUR.Y MEDIO AMBIENTE')
Subject.create(:code => 543, :name => 'PROYECTO DE PLANTA')
Subject.create(:code => 544, :name => 'HIG.Y SEG.LAB.EN LA CONSTRUC.')
Subject.create(:code => 546, :name => 'PROY.CALC.ESTR.METALICAS II')
Subject.create(:code => 547, :name => 'PROY.CALC.ESTRUCT.HORM.IV')
Subject.create(:code => 548, :name => 'PROYECTO ESTRUCTURAL II')
Subject.create(:code => 549, :name => 'CONTROL INDUSTRIAL')
Subject.create(:code => 551, :name => 'TRABAJO FINAL')
Subject.create(:code => 902, :name => 'F.G.:ESTRUCT.ECON.ARGENTINA')
Subject.create(:code => 903, :name => 'F.G.:TALLER EXP.CCIA/ARTE/TECN')
Subject.create(:code => 904, :name => 'F.G.:INVEST.AMB.INTERDISCIPL.')
Subject.create(:code => 905, :name => 'F.G.: DIRECCIÓN DE SISTEMAS')
Subject.create(:code => 906, :name => 'F.G.:COMPORT.HUM.EN LAS ORG.')
Subject.create(:code => 907, :name => 'F.G.:IMPACTOS DEL CBIO.GLOBAL')
