INSERT INTO subjects(code, name, created_at, updated_at) VALUES
(101, 'QUIMICA GENERAL', datetime('now'), datetime('now')),
(125, 'CÁLCULO ELEMENTAL', datetime('now'), datetime('now')),
(126, 'ALGEBRA Y GEOMETRÍA', datetime('now'), datetime('now')),
(127, 'INFORMÁTICA I', datetime('now'), datetime('now')),
(128, 'REPRESENTACIÓN GRAFICA', datetime('now'), datetime('now')),
(130, 'CÁLCULO AVANZADO', datetime('now'), datetime('now')),
(131, 'FÍSICA I', datetime('now'), datetime('now')),
(132, 'INFORMÁTICA II', datetime('now'), datetime('now')),
(135, 'INTROD.FIL.Y ANTROP.FILOSOFICA', datetime('now'), datetime('now')),
(207, 'FILOSOFIA II', datetime('now'), datetime('now')),
(219, 'INFORMATICA', datetime('now'), datetime('now')),
(223, 'FISICA II', datetime('now'), datetime('now')),
(225, 'ESTABILIDAD II', datetime('now'), datetime('now')),
(226, 'MECANICA', datetime('now'), datetime('now')),
(246, 'FÍSICA II', datetime('now'), datetime('now')),
(247, 'QUÍMICA GENERAL', datetime('now'), datetime('now')),
(248, 'MATEMÁTICA SUPERIOR', datetime('now'), datetime('now')),
(251, 'PROBABILIDAD Y ESTADÍSTICA', datetime('now'), datetime('now')),
(252, 'ELECTROTECNIA', datetime('now'), datetime('now')),
(253, 'MECÁNICA', datetime('now'), datetime('now')),
(254, 'MÉTODOS NUMÉRICOS', datetime('now'), datetime('now')),
(255, 'LABORATORIO DE INGENIERÍA', datetime('now'), datetime('now')),
(256, 'FÍSICA III', datetime('now'), datetime('now')),
(257, 'INGENIERIA, ECONOM.Y SOCIEDAD', datetime('now'), datetime('now')),
(258, 'ÉTICA Y METAFÍSICA', datetime('now'), datetime('now')),
(260, 'REPRESENT.GRAFICA APLICADA', datetime('now'), datetime('now')),
(302, 'BIOLOGIA Y MICROBIOLOGIA', datetime('now'), datetime('now')),
(303, 'TERMODINAMICA', datetime('now'), datetime('now')),
(304, 'REDES I', datetime('now'), datetime('now')),
(305, 'HIGIENE Y SEGURIDAD', datetime('now'), datetime('now')),
(311, 'INSTRUMENTOS Y MEDICIONES', datetime('now'), datetime('now')),
(312, 'MUESTREO Y EVAL.AMBIENTAL', datetime('now'), datetime('now')),
(313, 'TERMODINAMICA', datetime('now'), datetime('now')),
(314, 'ELECTROTECNIA I', datetime('now'), datetime('now')),
(318, 'TEOLOGIA I', datetime('now'), datetime('now')),
(320, 'TERMODINÁMICA', datetime('now'), datetime('now')),
(321, 'MECANICA DE LOS FLUIDOS', datetime('now'), datetime('now')),
(322, 'ESTADISTICA I', datetime('now'), datetime('now')),
(324, 'QUÍMICA DEL AMBIENTE', datetime('now'), datetime('now')),
(325, 'MUESTREO,EVAL.Y CTROL.AMBIENT.', datetime('now'), datetime('now')),
(326, 'MICROBIOLOGÍA AMBIENTAL', datetime('now'), datetime('now')),
(327, 'MECÁNICA DE LOS FLUIDOS', datetime('now'), datetime('now')),
(328, 'TERMODINÁMICA', datetime('now'), datetime('now')),
(329, 'REDES I', datetime('now'), datetime('now')),
(330, 'MAQUINAS Y MOTORES ELÉCTRICOS', datetime('now'), datetime('now')),
(331, 'ESTRUCTURA DE DATOS', datetime('now'), datetime('now')),
(332, 'ESTADÍSTICA APLICADA', datetime('now'), datetime('now')),
(333, 'ECONOMÍA GENERAL Y EMPRESARIA', datetime('now'), datetime('now')),
(334, 'TECNOLOGÍA MECÁNICA', datetime('now'), datetime('now')),
(335, 'MECÁNICA DE LOS FLUIDOS', datetime('now'), datetime('now')),
(351, 'ESTADISTICA', datetime('now'), datetime('now')),
(352, 'MATEMATICA IV', datetime('now'), datetime('now')),
(354, 'TERMODINÁMICA', datetime('now'), datetime('now')),
(358, 'ESTABILIDAD II', datetime('now'), datetime('now')),
(359, 'TOPOGRAFÍA Y GEODESIA', datetime('now'), datetime('now')),
(360, 'MECÁNICA DE SUELOS', datetime('now'), datetime('now')),
(361, 'INSTALACIONES DE EDIFICIOS', datetime('now'), datetime('now')),
(362, 'TEOLOGÍA FUNDAMENTAL', datetime('now'), datetime('now')),
(401, 'MECANICA DE LOS FLUIDOS', datetime('now'), datetime('now')),
(402, 'ELECTROTECNIA II', datetime('now'), datetime('now')),
(403, 'SIST.TRANSPORTES CONTAMINANTES', datetime('now'), datetime('now')),
(404, 'CONSTRUCCIONES DE HORMIGON I', datetime('now'), datetime('now')),
(406, 'BASES DE DATOS', datetime('now'), datetime('now')),
(407, 'TEOLOGIA II', datetime('now'), datetime('now')),
(408, 'ELECTROTECNIA', datetime('now'), datetime('now')),
(409, 'ESTADISTICA II', datetime('now'), datetime('now')),
(410, 'MECANICA DE SUELOS Y FUNDACIO.', datetime('now'), datetime('now')),
(412, 'COSTOS INDUSTRIALES', datetime('now'), datetime('now')),
(413, 'ELEMENTOS DE MAQUINAS', datetime('now'), datetime('now')),
(414, 'INGENIERÍA DE SOFTWARE II', datetime('now'), datetime('now')),
(415, 'LEGISLACIÓN PROFESIONAL', datetime('now'), datetime('now')),
(416, 'COMPLEJIDAD COMPUTACIONAL', datetime('now'), datetime('now')),
(417, 'REDES III', datetime('now'), datetime('now')),
(418, 'MAQUINAS TERMICAS', datetime('now'), datetime('now')),
(419, 'GESTION AMBIENTAL I', datetime('now'), datetime('now')),
(422, 'INSTALACIONES COMPLEMENTARIAS', datetime('now'), datetime('now')),
(424, 'CONSTRUC.METALICAS Y DE MADERA', datetime('now'), datetime('now')),
(426, 'ELECTRÓNICA III', datetime('now'), datetime('now')),
(427, 'REDES DE COMUN.DIGITALES II', datetime('now'), datetime('now')),
(428, 'TEORIA Y LABORAT.CTROL.AUTOM.', datetime('now'), datetime('now')),
(429, 'GESTIÓN AMBIENTAL I', datetime('now'), datetime('now')),
(430, 'HIGIENE Y SEGURIDAD LABORAL', datetime('now'), datetime('now')),
(431, 'MODELOS DE TRANSP.DE CONTAM.', datetime('now'), datetime('now')),
(432, 'ENERGÍA Y MEDIO AMBIENTE', datetime('now'), datetime('now')),
(436, 'TEOLOGÍA DOGMÁTICA', datetime('now'), datetime('now')),
(438, 'LEGISLACIÓN PROFESIONAL', datetime('now'), datetime('now')),
(439, 'ADMINISTRACIÓN DE EMPRESAS', datetime('now'), datetime('now')),
(440, 'ARQUITECTURA Y URBANISMO', datetime('now'), datetime('now')),
(443, 'PROY.CALC.ESTRUCT.HORM.II', datetime('now'), datetime('now')),
(444, 'DISEÑO GEOM.VIAS DE COMUNIC.', datetime('now'), datetime('now')),
(445, 'FERROCARRILES', datetime('now'), datetime('now')),
(446, 'PUERTOS Y VIAS NAVEGABLES', datetime('now'), datetime('now')),
(455, 'INVESTIGACIÓN OPERATIVA', datetime('now'), datetime('now')),
(458, 'COSTOS PARA INGENIEROS', datetime('now'), datetime('now')),
(459, 'ORGANIZACIÓN INDUSTRIAL II', datetime('now'), datetime('now')),
(460, 'PROCESOS INDUSTRIALES II', datetime('now'), datetime('now')),
(461, 'MAQUINAS TÉRMICAS', datetime('now'), datetime('now')),
(462, 'ANALISIS DE DECISIONES Y SIM.', datetime('now'), datetime('now')),
(463, 'PROCESOS INDUSTRIALES II', datetime('now'), datetime('now')),
(503, 'ORGAN.PROGRAM.CONTROL DE OBRAS', datetime('now'), datetime('now')),
(504, 'PUERTOS Y VIAS NAVEGABLES', datetime('now'), datetime('now')),
(507, 'DERECHO,POL.ORDENAM.AMBIENT.', datetime('now'), datetime('now')),
(509, 'DERECHO Y POLITICA AMBIENTAL', datetime('now'), datetime('now')),
(510, 'INGENIERIA ECONOMICA', datetime('now'), datetime('now')),
(511, 'GESTION DE LA CALIDAD', datetime('now'), datetime('now')),
(512, 'HIDRAULICA APLICADA', datetime('now'), datetime('now')),
(513, 'INGENIERIA SANITARIA', datetime('now'), datetime('now')),
(514, 'SIST.VIDEO Y PROCES.DE IMAGEN.', datetime('now'), datetime('now')),
(516, 'CONSTRUCCIONES DE HORMIGON II', datetime('now'), datetime('now')),
(517, 'PROYECTO DE ESTRUCTURAS', datetime('now'), datetime('now')),
(518, 'OPTOELECTRONICA', datetime('now'), datetime('now')),
(520, 'ADMINISTRACIÓN DE EMPRESAS', datetime('now'), datetime('now')),
(521, 'DIR.PROYECTOS DE SISTEMAS', datetime('now'), datetime('now')),
(522, 'INSTRUMENTACION Y CONTROL', datetime('now'), datetime('now')),
(523, 'SISTEMAS DIGITALES APLICADOS', datetime('now'), datetime('now')),
(524, 'AUDITORIA INFORMÁTICA', datetime('now'), datetime('now')),
(527, 'PROYECTO DE PLANTA', datetime('now'), datetime('now')),
(528, 'TEOLOGIA III', datetime('now'), datetime('now')),
(531, 'LOGISTICA', datetime('now'), datetime('now')),
(532, 'LEGISLACION GENERAL Y LABORAL', datetime('now'), datetime('now')),
(533, 'CARRETERAS Y AEROPUERTOS', datetime('now'), datetime('now')),
(534, 'COMUNICACIONES ÓPTICAS', datetime('now'), datetime('now')),
(535, 'ADMINISTRACIÓN DE EMPRESAS', datetime('now'), datetime('now')),
(536, 'ELECTRONICA Y CTROL.INDUSTRIAL', datetime('now'), datetime('now')),
(537, 'POLIT.Y LEGISLACION AMBIENTAL', datetime('now'), datetime('now')),
(538, 'LEGISLACIÓN PROFESIONAL', datetime('now'), datetime('now')),
(539, 'TEOL.MORAL Y DOCTR.SOC.IGLESIA', datetime('now'), datetime('now')),
(540, 'GESTIÓN DE LA CALIDAD', datetime('now'), datetime('now')),
(541, 'INGENIERÍA ECONÓMICA', datetime('now'), datetime('now')),
(542, 'HIG.SEGUR.Y MEDIO AMBIENTE', datetime('now'), datetime('now')),
(543, 'PROYECTO DE PLANTA', datetime('now'), datetime('now')),
(544, 'HIG.Y SEG.LAB.EN LA CONSTRUC.', datetime('now'), datetime('now')),
(546, 'PROY.CALC.ESTR.METALICAS II', datetime('now'), datetime('now')),
(547, 'PROY.CALC.ESTRUCT.HORM.IV', datetime('now'), datetime('now')),
(548, 'PROYECTO ESTRUCTURAL II', datetime('now'), datetime('now')),
(549, 'CONTROL INDUSTRIAL', datetime('now'), datetime('now')),
(551, 'TRABAJO FINAL', datetime('now'), datetime('now')),
(902, 'F.G.:ESTRUCT.ECON.ARGENTINA', datetime('now'), datetime('now')),
(903, 'F.G.:TALLER EXP.CCIA/ARTE/TECN', datetime('now'), datetime('now')),
(904, 'F.G.:INVEST.AMB.INTERDISCIPL.', datetime('now'), datetime('now')),
(905, 'F.G.: DIRECCIÓN DE SISTEMAS', datetime('now'), datetime('now')),
(906, 'F.G.:COMPORT.HUM.EN LAS ORG.', datetime('now'), datetime('now')),
(907, 'F.G.:IMPACTOS DEL CBIO.GLOBAL', datetime('now'), datetime('now'))
