CREATE TABLE IF NOT EXISTS `cei`.`students_raw` (
  `id` INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `code` VARCHAR(45) NULL,
  `name` VARCHAR(45) NULL)
ENGINE = MyISAM

CREATE TABLE students_raw (
    id INT NOT NULL AUTO_INCREMENT,
    code VARCHAR(45) NULL,
  	name VARCHAR(45) NULL)
     PRIMARY KEY (id)
) ENGINE=MyISAM;